### ISSUE TITLE
ERROR: No Subnets configured

### ISSUE THREAD

**Issue by manditri** [ace13/smart_proxy_dhcp_dnsmasq#19]
I have created a subnet in foreman. Dnsmasq is serving DHCP, DNS and TFTP. But PXE boot fails. When I turn on a machine on the same subnet it gets an IP successfully but I get an error from smart-proxy afterwards. See below error captured from the UI.

No subnets configured: /usr/lib/ruby/vendor_ruby/smart_proxy_dhcp_dnsmasq/dhcp_dnsmasq_subnet_service.rb:286:in `load_leases'
/usr/lib/ruby/vendor_ruby/smart_proxy_dhcp_dnsmasq/dhcp_dnsmasq_subnet_service.rb:45:in `block in watch_leases'
/usr/lib/ruby/vendor_ruby/rb-inotify/watcher.rb:41:in `callback!'
/usr/lib/ruby/vendor_ruby/rb-inotify/event.rb:128:in `callback!'
/usr/lib/ruby/vendor_ruby/rb-inotify/notifier.rb:243:in `block in process'
/usr/lib/ruby/vendor_ruby/rb-inotify/notifier.rb:242:in `each'
/usr/lib/ruby/vendor_ruby/rb-inotify/notifier.rb:242:in `process'
/usr/lib/ruby/vendor_ruby/rb-inotify/notifier.rb:225:in `run'
/usr/lib/ruby/vendor_ruby/smart_proxy_dhcp_dnsmasq/dhcp_dnsmasq_subnet_service.rb:60:in `watch_leases'
/usr/lib/ruby/vendor_ruby/smart_proxy_dhcp_dnsmasq/dhcp_dnsmasq_subnet_service.rb:70:in `block in start'
/usr/lib/ruby/vendor_ruby/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

**Comment by darkglade** [comment]
This is probably because you don't have the netmask in your dhcp-range declaration it HAS to be in the format;
`dhcp-range=<start IP>,<end IP>,<netmask>,<ttl>`

I've raised a PR https://github.com/theforeman/smart_proxy_dhcp_dnsmasq/pull/22 to document this and another issue I discovered around dhcp-host records.
